//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/arbeidstaker/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Arbeidstaker", Namespace="http://fk.no/fint/arbeidstaker/1.0", IsNullable=false)]
public partial class ArbeidstakerType : AbstraktPersonType {
    
    private StillingType[] stillingerField;
    
    private PeriodeType ansettelsesperiodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("stilling", IsNullable=false)]
    public StillingType[] stillinger {
        get {
            return this.stillingerField;
        }
        set {
            this.stillingerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PeriodeType ansettelsesperiode {
        get {
            return this.ansettelsesperiodeField;
        }
        set {
            this.ansettelsesperiodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/arbeidstaker/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Stilling", Namespace="http://fk.no/fint/arbeidstaker/1.0", IsNullable=false)]
public partial class StillingType {
    
    private string avdelingField;
    
    private string funksjonField;
    
    private double grunnlonnField;
    
    private string organisasjonField;
    
    private string statusField;
    
    private string stillingskodeField;
    
    private string stillingsnummerField;
    
    private System.Nullable<double> stillingsprosentField;
    
    private bool stillingsprosentFieldSpecified;
    
    private string stillingstittelField;
    
    private string ansettelsestypeField;
    
    private PeriodeType stillingsperiodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string avdeling {
        get {
            return this.avdelingField;
        }
        set {
            this.avdelingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string funksjon {
        get {
            return this.funksjonField;
        }
        set {
            this.funksjonField = value;
        }
    }
    
    /// <remarks/>
    public double grunnlonn {
        get {
            return this.grunnlonnField;
        }
        set {
            this.grunnlonnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string organisasjon {
        get {
            return this.organisasjonField;
        }
        set {
            this.organisasjonField = value;
        }
    }
    
    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string stillingskode {
        get {
            return this.stillingskodeField;
        }
        set {
            this.stillingskodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string stillingsnummer {
        get {
            return this.stillingsnummerField;
        }
        set {
            this.stillingsnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> stillingsprosent {
        get {
            return this.stillingsprosentField;
        }
        set {
            this.stillingsprosentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stillingsprosentSpecified {
        get {
            return this.stillingsprosentFieldSpecified;
        }
        set {
            this.stillingsprosentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string stillingstittel {
        get {
            return this.stillingstittelField;
        }
        set {
            this.stillingstittelField = value;
        }
    }
    
    /// <remarks/>
    public string ansettelsestype {
        get {
            return this.ansettelsestypeField;
        }
        set {
            this.ansettelsestypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PeriodeType stillingsperiode {
        get {
            return this.stillingsperiodeField;
        }
        set {
            this.stillingsperiodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Periode", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class PeriodeType {
    
    private System.DateTime startField;
    
    private System.DateTime sluttField;
    
    /// <remarks/>
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime slutt {
        get {
            return this.sluttField;
        }
        set {
            this.sluttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Personnavn", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class PersonnavnType {
    
    private string fornavnField;
    
    private string etternavnField;
    
    /// <remarks/>
    public string fornavn {
        get {
            return this.fornavnField;
        }
        set {
            this.fornavnField = value;
        }
    }
    
    /// <remarks/>
    public string etternavn {
        get {
            return this.etternavnField;
        }
        set {
            this.etternavnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Landkode", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class LandkodeType {
    
    private string kodeField;
    
    private string beskrivelseField;
    
    /// <remarks/>
    public string kode {
        get {
            return this.kodeField;
        }
        set {
            this.kodeField = value;
        }
    }
    
    /// <remarks/>
    public string beskrivelse {
        get {
            return this.beskrivelseField;
        }
        set {
            this.beskrivelseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Adresse", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class AdresseType {
    
    private string adressetypeField;
    
    private string adresseField;
    
    private string postnummerField;
    
    private string poststedField;
    
    private LandkodeType landField;
    
    /// <remarks/>
    public string adressetype {
        get {
            return this.adressetypeField;
        }
        set {
            this.adressetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string adresse {
        get {
            return this.adresseField;
        }
        set {
            this.adresseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string postnummer {
        get {
            return this.postnummerField;
        }
        set {
            this.postnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string poststed {
        get {
            return this.poststedField;
        }
        set {
            this.poststedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LandkodeType land {
        get {
            return this.landField;
        }
        set {
            this.landField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Kontaktinformasjon", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class KontaktinformasjonType {
    
    private string epostadresseField;
    
    private string telefonnummerField;
    
    private string mobiltelefonummerField;
    
    private string webstedField;
    
    private string kontakttypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string epostadresse {
        get {
            return this.epostadresseField;
        }
        set {
            this.epostadresseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string telefonnummer {
        get {
            return this.telefonnummerField;
        }
        set {
            this.telefonnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string mobiltelefonummer {
        get {
            return this.mobiltelefonummerField;
        }
        set {
            this.mobiltelefonummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string websted {
        get {
            return this.webstedField;
        }
        set {
            this.webstedField = value;
        }
    }
    
    /// <remarks/>
    public string kontakttype {
        get {
            return this.kontakttypeField;
        }
        set {
            this.kontakttypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Identifikator", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class IdentifikatorType {
    
    private string identifikatorverdiField;
    
    private string identifikatortypeField;
    
    private System.Nullable<System.DateTime> utstedtdatoField;
    
    private bool utstedtdatoFieldSpecified;
    
    private string utstedtAvAutoritetField;
    
    private PeriodeType gyldighetsperiodeField;
    
    /// <remarks/>
    public string identifikatorverdi {
        get {
            return this.identifikatorverdiField;
        }
        set {
            this.identifikatorverdiField = value;
        }
    }
    
    /// <remarks/>
    public string identifikatortype {
        get {
            return this.identifikatortypeField;
        }
        set {
            this.identifikatortypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> utstedtdato {
        get {
            return this.utstedtdatoField;
        }
        set {
            this.utstedtdatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool utstedtdatoSpecified {
        get {
            return this.utstedtdatoFieldSpecified;
        }
        set {
            this.utstedtdatoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string utstedtAvAutoritet {
        get {
            return this.utstedtAvAutoritetField;
        }
        set {
            this.utstedtAvAutoritetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PeriodeType gyldighetsperiode {
        get {
            return this.gyldighetsperiodeField;
        }
        set {
            this.gyldighetsperiodeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstraktPersonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ArbeidstakerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstraktEnhetType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("AbstraktAktoer", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public abstract partial class AbstraktAktoerType {
    
    private IdentifikatorType[] identifikatorerField;
    
    private KontaktinformasjonType[] kontaktinformasjonerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("identifikator", IsNullable=false)]
    public IdentifikatorType[] identifikatorer {
        get {
            return this.identifikatorerField;
        }
        set {
            this.identifikatorerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("kontaktinformasjon", IsNullable=false)]
    public KontaktinformasjonType[] kontaktinformasjoner {
        get {
            return this.kontaktinformasjonerField;
        }
        set {
            this.kontaktinformasjonerField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ArbeidstakerType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("AbstraktPerson", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public abstract partial class AbstraktPersonType : AbstraktAktoerType {
    
    private string fulltNavnField;
    
    private PersonnavnType navnField;
    
    private System.Nullable<KjoennType> kjoennField;
    
    private bool kjoennFieldSpecified;
    
    private LandkodeType statsborgerskapField;
    
    private System.Nullable<System.DateTime> foedselsdatoField;
    
    private bool foedselsdatoFieldSpecified;
    
    private System.Nullable<SivilstandType> sivilstandField;
    
    private bool sivilstandFieldSpecified;
    
    private AdresseType[] adresserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string fulltNavn {
        get {
            return this.fulltNavnField;
        }
        set {
            this.fulltNavnField = value;
        }
    }
    
    /// <remarks/>
    public PersonnavnType navn {
        get {
            return this.navnField;
        }
        set {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<KjoennType> kjoenn {
        get {
            return this.kjoennField;
        }
        set {
            this.kjoennField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kjoennSpecified {
        get {
            return this.kjoennFieldSpecified;
        }
        set {
            this.kjoennFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LandkodeType statsborgerskap {
        get {
            return this.statsborgerskapField;
        }
        set {
            this.statsborgerskapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> foedselsdato {
        get {
            return this.foedselsdatoField;
        }
        set {
            this.foedselsdatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool foedselsdatoSpecified {
        get {
            return this.foedselsdatoFieldSpecified;
        }
        set {
            this.foedselsdatoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<SivilstandType> sivilstand {
        get {
            return this.sivilstandField;
        }
        set {
            this.sivilstandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sivilstandSpecified {
        get {
            return this.sivilstandFieldSpecified;
        }
        set {
            this.sivilstandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("adresse", IsNullable=false)]
    public AdresseType[] adresser {
        get {
            return this.adresserField;
        }
        set {
            this.adresserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
public enum KjoennType {
    
    /// <remarks/>
    kvinne,
    
    /// <remarks/>
    mann,
    
    /// <remarks/>
    ubestemt,
    
    /// <remarks/>
    ukjent,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
public enum SivilstandType {
    
    /// <remarks/>
    ugift,
    
    /// <remarks/>
    gift,
    
    /// <remarks/>
    enkeEllerEnkemann,
    
    /// <remarks/>
    skilt,
    
    /// <remarks/>
    separert,
    
    /// <remarks/>
    registrertPartner,
    
    /// <remarks/>
    separertPartner,
    
    /// <remarks/>
    skiltPartner,
    
    /// <remarks/>
    gjenlevendePartner,
    
    /// <remarks/>
    uoppgitt,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("AbstraktEnhet", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public abstract partial class AbstraktEnhetType : AbstraktAktoerType {
    
    private string organisasjonsnummerField;
    
    private string navnField;
    
    private string organisasjonsformField;
    
    private string[] naeringskodeField;
    
    private AdresseType adresseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string organisasjonsnummer {
        get {
            return this.organisasjonsnummerField;
        }
        set {
            this.organisasjonsnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string navn {
        get {
            return this.navnField;
        }
        set {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string organisasjonsform {
        get {
            return this.organisasjonsformField;
        }
        set {
            this.organisasjonsformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("naeringskode", IsNullable=true)]
    public string[] naeringskode {
        get {
            return this.naeringskodeField;
        }
        set {
            this.naeringskodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AdresseType adresse {
        get {
            return this.adresseField;
        }
        set {
            this.adresseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fk.no/fint/felles/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Spraak", Namespace="http://fk.no/fint/felles/1.0", IsNullable=false)]
public partial class SpraakType {
    
    private string kodeField;
    
    private string beskrivelseField;
    
    /// <remarks/>
    public string kode {
        get {
            return this.kodeField;
        }
        set {
            this.kodeField = value;
        }
    }
    
    /// <remarks/>
    public string beskrivelse {
        get {
            return this.beskrivelseField;
        }
        set {
            this.beskrivelseField = value;
        }
    }
}
